// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgIcje1LlDGjsVkqFojGW_xcEZKl0dtI',
    appId: '1:95276966425:web:41577bab334055c8024088',
    messagingSenderId: '95276966425',
    projectId: 'flutterforms-44b1f',
    authDomain: 'flutterforms-44b1f.firebaseapp.com',
    storageBucket: 'flutterforms-44b1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Pmn5KbMbMbDj-pj_x-xMYBlgzXXb6OU',
    appId: '1:95276966425:android:d7e85d02b61c5c48024088',
    messagingSenderId: '95276966425',
    projectId: 'flutterforms-44b1f',
    storageBucket: 'flutterforms-44b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAyTNT8G2y6uGFDiH6UA-baiLyN-qt5mI',
    appId: '1:95276966425:ios:e6cc1433a9fbc351024088',
    messagingSenderId: '95276966425',
    projectId: 'flutterforms-44b1f',
    storageBucket: 'flutterforms-44b1f.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAyTNT8G2y6uGFDiH6UA-baiLyN-qt5mI',
    appId: '1:95276966425:ios:e6cc1433a9fbc351024088',
    messagingSenderId: '95276966425',
    projectId: 'flutterforms-44b1f',
    storageBucket: 'flutterforms-44b1f.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAgIcje1LlDGjsVkqFojGW_xcEZKl0dtI',
    appId: '1:95276966425:web:bc1d4315a511c9aa024088',
    messagingSenderId: '95276966425',
    projectId: 'flutterforms-44b1f',
    authDomain: 'flutterforms-44b1f.firebaseapp.com',
    storageBucket: 'flutterforms-44b1f.appspot.com',
  );
}
